### PR TITLE
Bug fix deep fetch block array

### LINKED ISSUE #5: TypeError: no implicit conversion of Symbol into Integer
When attempting to return an array as a default value, `deep_fetch` raises a `TypeError`. For example:

``` ruby
{ foo: :bar }.deep_fetch(:boo, :baz) { [] }
# => TypeError: no implicit conversion of Symbol into Integer
```

### PR DESCRIPTION
**Pull request by rossta**
Fixes #5 

Reimplements deep_fetch to avoid recursion

### CODE REVIEW

**Comment by vzvu3k6k** [comment]
With this patch, `{:foo => 0}.deep_fetch(:foo, :bar) { :error }` is evaluated as `0`, not `:error`. (Ref. https://github.com/vzvu3k6k/deep_fetch/commit/38afa97c14bbceaef96973d2d7396814d1787608)

And until `value` is an array, the keys which are not kind of Integer is just dropped. So `{:foo => [:bar]}.deep_fetch(:foo, :baz) { :error }` is evaluated as `[:bar]`, not `:error`. Is that intended?

**Comment by rossta** [comment]
Good catch, looks I'm missing test cases and need to rethink implementation.

**Comment by vzvu3k6k** [comment]
I feel the problem is the current implementation of `deep_fetch` tries to fetch the return value of the block. I think of some solutions of it:
1. Use [hashie/deep_fetch](https://github.com/intridea/hashie/blob/master/lib/hashie/extensions/deep_fetch.rb)
2. Use `rescue` instead of a block, like `{ foo: :bar }.deep_fetch(:boo, :baz) rescue []`
3. Fix deep_fetch to return the value immediately when `Hash#fetch` fails

**Comment by rossta** [comment]
Yeah, I was taking a look at hashie/deep_fetch, might be a better alternative for me. Speaking to your third point, could be an implementation using `try/catch` like https://gist.github.com/avdi/1051967 although that example doesn't cover all the test cases.

**Pull request closed without merging**
